[CI] Drop push from check-links for now

diff --git a/.github/workflows/check-links.yml b/.github/workflows/check-links.yml
--- a/.github/workflows/check-links.yml
+++ b/.github/workflows/check-links.yml
@@ -7,7 +7,7 @@ on:
 
 env:
   CHANGED_FILES:
-  PR_NUM: ${{ github.event.issue.number }}
+  PR_NUM: ${{ github.event.pull_request.number }}
   USER_EMAIL: 107717825+opentelemetrybot@users.noreply.github.com
   USER_NAME: opentelemetrybot
 
@@ -55,36 +55,6 @@ jobs:
           echo "CHANGED_FILES=$CHANGED_FILES" >> "$GITHUB_ENV"
         continue-on-error: true
 
-      - name: Push changes if any, and fail check
-        if: ${{ env.CHANGED_FILES }}
-        run: |
-          echo "Changes detected in the refcache etc:"
-          git status --short
-
-          gh pr checkout $PR_NUM -b "pr-check-links-${RANDOM}"
-          git branch -v
-
-          git config --local user.email "$USER_EMAIL"
-          git config --local user.name "$USER_NAME"
-          git add -A
-          git commit -m "Updates from build-and-check-links workflow"
-
-          echo "\nPushing changes to PR."
-          current_branch=$(git rev-parse --abbrev-ref HEAD)
-          echo current_branch=$current_branch
-          # gh pr checkout sets some git configs that we can use to make sure
-          # we push to the right repo & to the right branch
-          remote_repo=$(git config --get branch.${current_branch}.remote)
-          echo remote_repo=$remote_repo
-          remote_branch=$(git config --get branch.${current_branch}.merge)
-          echo remote_branch=$remote_branch
-          git push ${remote_repo} HEAD:${remote_branch}
-
-          echo "Failing workflow so that changes can be reviewed, and checks rerun."
-          exit 1
-        env:
-          GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
-
       - uses: actions/upload-artifact@v4
         with:
           name: build-log-etc
@@ -92,6 +62,36 @@ jobs:
             tmp/build-log.txt
             tmp/package*.json
             static/refcache.json
+
+      - name: Push changes if any, and fail check
+        if: ${{ env.CHANGED_FILES }}
+        run: |
+          echo "Changes detected in the refcache etc:"
+          git status --short
+
+          echo 'cmd: gh pr checkout $PR_NUM -b "pr-check-links-${RANDOM}"'
+        #   git branch -v
+
+        #   git config --local user.email "$USER_EMAIL"
+        #   git config --local user.name "$USER_NAME"
+        #   git add -A
+        #   git commit -m "Updates from build-and-check-links workflow"
+
+        #   echo "\nPushing changes to PR."
+        #   current_branch=$(git rev-parse --abbrev-ref HEAD)
+        #   echo current_branch=$current_branch
+        #   # gh pr checkout sets some git configs that we can use to make sure
+        #   # we push to the right repo & to the right branch
+        #   remote_repo=$(git config --get branch.${current_branch}.remote)
+        #   echo remote_repo=$remote_repo
+        #   remote_branch=$(git config --get branch.${current_branch}.merge)
+        #   echo remote_branch=$remote_branch
+        #   git push ${remote_repo} HEAD:${remote_branch}
+
+        #   echo "Failing workflow so that changes can be reviewed, and checks rerun."
+        #   exit 1
+        # env:
+        #   GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
 
   check-refcache:
     name: REFCACHE updates?
